services:
  postgres:
    ports:
    - "5432:5432"
    image: postgres:17
    container_name: springblog-postgres
    restart: always
    env_file:
      - container-variables.env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: