-- Criação da tabela de Usuários
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       username VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL UNIQUE,
                       password VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP(6),
                       PRIMARY KEY (id)
);

-- Criação da tabela de Posts
CREATE TABLE posts (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       title VARCHAR(255),
                       content TEXT,
                       category VARCHAR(255) CHECK (category IN ('COMEDY', 'NEWS', 'CELEBRITIES', 'FITNESS')),
                       author_id BIGINT NOT NULL,
                       created_at TIMESTAMP(6),
                       PRIMARY KEY (id)
);

-- Criação da tabela de Comentários
CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                          content TEXT,
                          author_id BIGINT,
                          post_id BIGINT,
                          created_at TIMESTAMP(6),
                          PRIMARY KEY (id)
);

-- Adicionando os Relacionamentos (Chaves Estrangeiras)
ALTER TABLE IF EXISTS comments
    ADD CONSTRAINT FKn2na60ukhs76ibtpt9burkm27 FOREIGN KEY (author_id) REFERENCES users;

ALTER TABLE IF EXISTS comments
    ADD CONSTRAINT FKh4c7lvsc298whoyd4w9ta25cr FOREIGN KEY (post_id) REFERENCES posts;

ALTER TABLE IF EXISTS posts
    ADD CONSTRAINT FK6xvn0811tkyo3nfjk2xvqx6ns FOREIGN KEY (author_id) REFERENCES users;